version: '3.8'

services:
  videochat:
    build: .
    container_name: videochat-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start
